# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: deploy to test

on: workflow_dispatch

jobs:
  print:
    steps:
      - name: printing message
        run: echo "Running test yml file"

  deploy-test:
  uses: ./.github/workflows/build.yml
  with:
    repository: ${{ github.event.repository.name }}
    base_namespace: api-test
