# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    environment: 
      name: prod
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: printing secrets
      run: echo "ENVIRONMENT_PROD_SECRET ${{secrets.ENVIRONMENT_PROD_SECRET}} ,ENVIRONMENT_PROD_SECRET ${{secrets.REPOSITORY_PROD_SECRET}} , REPOSITORY_PROD_SECRET ${{secrets.ORGANISATION_PROD_SECRET}} "
      
